[SERVICE]
    Flush         5
    Log_Level     info
    Parsers_File  /fluent-bit/etc/parsers.conf


[INPUT]
    Name            tail
    Tag             docker.*
    Path            /var/lib/docker/containers/*/*-json.log
    Path_Key        source_file
    Parser          docker
    DB              /var/log/flb_docker.db
    Mem_Buf_Limit   5MB
    Skip_Long_Lines On

[FILTER]
    Name          record_modifier
    Match         docker.*
    Record        host ${HOSTNAME}
    Record        environment ${LOG_ENV}

[OUTPUT]
    Name              s3
    Match             *
    bucket            rinaahmd-polyai-logs-228281126655
    region            us-east-1
    s3_key_format     /${LOG_ENV}/logs/%Y/%m/%d/$TAG[1]_%H%M%S.gz
    compression       gzip
    upload_timeout    60s
    use_put_object    On
    total_file_size   1M
