[SERVICE]
    Flush         5
    Log_Level     info
    Parsers_File  /fluent-bit/etc/parsers.conf

[INPUT]
    Name          tail
    Tag           docker.*
    Path          /var/lib/docker/containers/*/*-json.log
    Path_Key      source
    Parser        docker
    DB            /var/log/flb_docker.db
    Mem_Buf_Limit 5MB
    Skip_Long_Lines On

[FILTER]
    Name          record_modifier
    Match         docker.*
    Record        host ${HOSTNAME}

[FILTER]
    Name          rewrite_tag
    Match         docker.*
    Rule          $attrs['com.docker.compose.service'] ^(.+)$ logs.$1 false
    Emitter_Name  service_logs

[OUTPUT]
    Name              s3
    Match             logs.*
    bucket            ${S3_LOGS_BUCKET}
    region            ${AWS_REGION}
    s3_key_format     /${LOG_ENV}/logs/host=${HOSTNAME}/service=$TAG[1]/%Y/%m/%d/%H/%M/%S/$UUID.gz
    compression       gzip
    upload_timeout    60s
    use_put_object    On
    total_file_size   1M
