apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: ebs-sc

  volumeName: prometheus-dev-pv

  resources:
    requests:
      storage: 5Gi