apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-dev-pv
spec:
  capacity:
    storage: 5Gi

  volumeMode: Filesystem

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  storageClassName: ebs-sc

  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0c524fc2962c89bde
    fsType: ext4

  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - us-east-1b