apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo
  namespace: dev
  labels:
    app: yolo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
      labels:
        app: yolo
    spec:
      containers:
        - name: yolo
          image: rinaahmd/yolo-service:0.0.1
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_S3_BUCKET
              value: rina-polyai-images
---
apiVersion: v1
kind: Service
metadata:
  name: yolo
  namespace: dev
spec:
  selector:
    app: yolo
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
