apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: agent
  namespace: prod
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - prod
  selector:
    matchLabels:
      app: agent
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: yolo
  namespace: prod
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - prod
  selector:
    matchLabels:
      app: yolo
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
