apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rinaahmd/PolyAIFursa-Private.git
    targetRevision: main
    path: infra/k8s/prod
    directory:
      include: "agent.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
